# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(986, 644)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(70, 30, 881, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 101, 20))
        self.label_2.setObjectName("label_2")
        self.name_edit = QtWidgets.QLineEdit(parent=Form)
        self.name_edit.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.name_edit.setObjectName("name_edit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 111, 20))
        self.label_3.setObjectName("label_3")
        self.st_edit = QtWidgets.QLineEdit(parent=Form)
        self.st_edit.setGeometry(QtCore.QRect(150, 130, 113, 20))
        self.st_edit.setObjectName("st_edit")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.label_4.setObjectName("label_4")
        self.type_edit = QtWidgets.QComboBox(parent=Form)
        self.type_edit.setGeometry(QtCore.QRect(150, 170, 111, 22))
        self.type_edit.setObjectName("type_edit")
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setGeometry(QtCore.QRect(150, 210, 371, 101))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 91, 20))
        self.label_5.setObjectName("label_5")
        self.cost_edit = QtWidgets.QLineEdit(parent=Form)
        self.cost_edit.setGeometry(QtCore.QRect(150, 330, 113, 20))
        self.cost_edit.setObjectName("cost_edit")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(80, 330, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(50, 370, 91, 16))
        self.label_7.setObjectName("label_7")
        self.volume_edit = QtWidgets.QLineEdit(parent=Form)
        self.volume_edit.setGeometry(QtCore.QRect(150, 370, 113, 20))
        self.volume_edit.setObjectName("volume_edit")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(180, 430, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "При вводе названия сорта, уже имеющегося в базе, информация в БД изменится. При вводе сорта, которого нет в базе, будет добавлен новый сорт."))
        self.label_2.setText(_translate("Form", "Название сорта"))
        self.label_3.setText(_translate("Form", "Степень обжарки"))
        self.label_4.setText(_translate("Form", "Молотый / в зёрнах"))
        self.label_5.setText(_translate("Form", "Описание вкуса"))
        self.label_6.setText(_translate("Form", "Цена"))
        self.label_7.setText(_translate("Form", "Объём упаковки"))
        self.pushButton.setText(_translate("Form", "ОК"))
